### PR TITLE
[DOCS] adding the license key to the bower.json

### LINKED ISSUE #72: [DOC] add the license key to the bower.json
I need this change to allow the `bower-license` node module to check all the licenses in our bower dependencies for a security audit. It appears that the [main repo](https://github.com/emberjs/ember.js/blob/master/LICENSE) has an MIT license.

Given that all that is required is a `"license": "MIT",` in the bower.json.

Thanks!

### PR DESCRIPTION
**Pull request by williamsbdev**
We are doing a security audit of all the dependencies in our bower.json. We are using the `bower-license` node module and it is searching the bower.json for the license key. This would allow us to programmatically show our security folks that we are using libraries with an acceptable license.

This would close #72.

### CODE REVIEW

**Comment by bmac** [comment]
Hi @williamsbdev. Thanks for the pr. Do you mind making this change in this file https://github.com/emberjs/data/blob/master/config/package-manager-files/bower.json in the main repo? The bower.json file in this repo is generated from that file every time we do a release.

**Comment by williamsbdev** [comment]
@bmac I will make that change right now. Thanks!

**Comment by williamsbdev** [comment]
@bmac it looks like you referenced the ember-data repo. I see that the ember-data does not have the license. However, the corresponding file in the emberjs repo https://github.com/williamsbdev/ember.js/blob/master/config/package_manager_files/bower.json does have the license key. Do you know why it is not showing up in this repo?

**Comment by williamsbdev** [comment]
It looks like this is the file that actually builds this repo? https://github.com/williamsbdev/ember.js/blob/master/bin/bower_ember_build

**Comment by bmac** [comment]
Opps sorry @williamsbdev. I forgot I was subscribed to this repo and assumed this was an issue on the components/ember-data repo when I saw the email.

Looks like you are correct and the bower.json file in the main repo already has the license key. The build script you linked is responsible for publishing the `release`, `beta` and `canary` branches on this repo and it looks like it is correctly copying the bower.json file from the main repo. https://github.com/components/ember/blob/release/bower.json#L4

As for why the license key isn't showing up in the tagged builds I suspect its because that process doesn't use the same `bower_ember_build` script. 

I suspect @rwjblue is the best one to decide if this pr should be merged here or if there is a workflow change that needs to be made to copy bower.json from the ember build into this repo.

**Comment by williamsbdev** [comment]
@bmac and @rwjblue it appears that the [file](https://github.com/williamsbdev/ember.js/blob/master/bin/bower_ember_build) I referenced above is only copying the `dist/` directory to this repo so my PR should be appropriate to fix this issue unless you would like me to modify the `bower_ember_build` script to also copy over the bower.json. Let me know how I can help out.

Thanks!

**Comment by rwjblue** [comment]
Can you ensure the other files have a valid license type as well (`package.json`, `composer.json`, etc)?

**Comment by williamsbdev** [comment]
I have added the license to the `package.json` and `component.json`. The `composer.json` already had the license.

**Comment by rwjblue** [comment]
Thanks!

**Comment by williamsbdev** [comment]
Thank you for getting this resolved so quickly! This will make my security friends very happy. :+1:

**Pull request merged**
